before:
  hooks:
    - go mod download
env:
  - CGO_ENABLED=0
  - GOPROXY=https://proxy.golang.org
project_name: certjunkie

builds:
  - id: builds
    goos:
      - linux
    goarch:
      - amd64
      - arm64

    main: main.go

dockers_v2:
  - dockerfile: Dockerfile.goreleaser
    images:
      - "{{ .Env.DOCKER_HUB_REPO }}"
      - "{{ .Env.DOCKER_GITHUB_REPO }}"
    tags:
      - "{{ .Version }}"
      - "latest"
    labels:
      "org.opencontainers.image.description": "CertJunkie"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
  footer: |
    **Full Changelog**: https://github.com/project0/certjunkie/compare/{{ .PreviousTag }}...{{ .Tag }}