FROM golang:1.25-alpine AS builder

FROM scratch
ARG TARGETPLATFORM

WORKDIR /root/
COPY --from=builder /etc/ssl/certs /etc/ssl/certs

COPY $TARGETPLATFORM/certjunkie /certjunkie
ENTRYPOINT ["/certjunkie"]

CMD [ "server" ]