---
name: publish github release artifacts with goreleaser
on:
  push:
    tags: '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: steps.setup-go.outputs.cache-hit != 'true'
        run: go mod download

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          DOCKER_GITHUB_REPO: ghcr.io/${{ github.actor }}/${{ github.repository }}
          DOCKER_HUB_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/certjunkie
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}