---
name: publish github release artifacts with goreleaser
on:
  push:
    tags: '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          DOCKER_GITHUB_REPO: ghcr.io/${{ github.actor }}/${{ github.repository }}
          DOCKER_HUB_REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/certjunkie
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}