# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
#  pull_request:
#    paths-ignore:
#      - "README.md"
  push:
    paths-ignore:
      - "README.md"

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Build and test
  test:
    name: Test golang
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - if: steps.setup-go.outputs.cache-hit != 'true'
        run: go mod download

      - run: go build -v .
      - run: go test -v -cover ./...

  # test goreleaser build
  goreleaser-snapshot:
    name: Test goreleaser
    runs-on: ubuntu-latest
    needs:
      - test
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"

      - if: steps.setup-go.outputs.cache-hit != 'true'
        run: go mod download

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --snapshot --clean
        env:
          DOCKER_GITHUB_REPO: local
          DOCKER_HUB_REPO: local
